<?php

/**
 * @file
 * Contains nolanextensions.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function nolanextensions_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the nolanextensions module.
    case 'help.page.nolanextensions':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Nolan Extensions') . '</p>';
      return $output;

    default:
  }
}
