name: nolan-tech-app
proxy:
  appserver:
    - nolantechapp.lndo.site:8080
services:
  appserver:
    type: node:10
    port: 8080
    run:
      - npm install --global @gridsome/cli
tooling:
  npm:
    type: node
    service: appserver
  gridsome:
    service: appserver
  develop:
    service: appserver
    cmd: gridsome develop --host 0.0.0.0 --port 8080
