name: nolan-tech-app
proxy:
  appserver:
    - nolan-tech-app.lndo.site:8080
services:
  appserver:
    type: node:10
    run:
      - npm install --global @gridsome/cli
tooling:
  npm:
    type: node
    service: appserver
  gridsome:
    service: appserver
  develop:
    service: appserver
    cmd: gridsome develop
